name = "BiApprox"
uuid = "6b23c94a-2afc-11e9-1d49-5131b50f74df"
authors = ["Jesus Mejia <jesusmejded@gmail.com>"]
version = "0.1.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
